# Generated by Django 3.2.7 on 2021-09-08 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_serial',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 8, 17, 5, 58, 858264, tzinfo=utc)),
        ),
    ]
