# Generated by Django 3.2.7 on 2021-09-07 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_auto_20210907_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_card', to='fraud_detection.card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 8, 58, 51, 788264, tzinfo=utc)),
        ),
    ]
