# Generated by Django 3.2.7 on 2021-09-14 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0005_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 14, 20, 54, 57, 769156, tzinfo=utc)),
        ),
    ]
