# Generated by Django 3.2.7 on 2021-09-14 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0006_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 14, 21, 5, 15, 32393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='question',
            field=models.ManyToManyField(blank=True, to='fraud_detection.SecurityQuestion'),
        ),
    ]
